#!/bin/sh

cmd_out=$(acpi -b)
bat_percent=$(echo $cmd_out | awk '{print $4}' | tr -d ',' | tr -d '%')
bat_status=$(echo $cmd_out | awk '{print $3}' | tr -d ',' | tr '[:upper:]' '[:lower:]')
load_time=$(echo $cmd_out | awk '{print $5}')

icon=
if [ $bat_percent -eq 100 ]; then
    icon=
elif [ $bat_percent -lt 76 ]; then
    icon=
elif [ $bat_percent -lt 51 ]; then
    icon=
elif [ $bat_percent -lt 26 ]; then
    icon=
else
    icon=
fi

[ $bat_status = "full" ] && echo ${icon} ${bat_percent}% || echo ${icon} ${bat_status}% $bat_percent \($load_time\)

exit 0
