#!/bin/sh

cmd_out=$(acpi -b)
bat_percent=$(echo $cmd_out | awk '{print $4}' | tr -d ',' | tr -d '%')
bat_status=$(echo $cmd_out | awk '{print $3}' | tr -d ',' | tr '[:upper:]' '[:lower:]')
load_time=$(echo $cmd_out | awk '{print $5}')

if [ $bat_percent -gt 75 ]; then
    icon=
elif [ $bat_percent -lt 76 ] && [ $bat_percent -gt 50 ]; then
    icon=
elif [ $bat_percent -lt 51 ] && [ $bat_percent -gt 25 ]; then
    icon=
elif [ $bat_percent -lt 26 ] && [ $bat_percent -gt 5 ]; then
    icon=
else
    icon=
fi

[ $bat_status = "full" ] && echo ${icon}\ ${bat_percent}% || echo ${icon}\ ${bat_status} ${bat_percent}% \($load_time\)

exit 0
