#!/bin/sh

get_ip_addr()
{
    ip_addr=$(ip addr show dev $1 | grep -w "inet" | awk '{print $2}' | cut -f1 -d'/')
    echo $ip_addr
}

output="offline" #default state
iface_list=$(ip addr show | grep '^[2-3]:' | awk '{print $2}' | tr -d ':')

for iface in $iface_list ; do
    ip_addr=$(get_ip_addr $iface)

    ! [ -z $ip_addr ] && output="$iface : $ip_addr" && break
done

echo $output

exit 0
